### ISSUE TITLE
To much padding in Site Header

### ISSUE THREAD

**Issue by fidoedidoe** [BodhiDev/bodhi-wp#3]
Desired outcome: Padding in the site header is reduced by 25-50% to bring more content in view

Impact area: Desktop / Tablet View (not mobile view)

Verified using: Chrome Desktop

Notes:
Relatively, there's a lot of "unused" space in the site header as a result of padding. It could be argued that this space is pushing the more valuable content out of view. 

Anyone with an eye for design / UX should verify this before actioning any change.

**Comment by ErwanGleo** [comment]
Ok modified it, there was a fixed height on the header.

**Comment by fidoedidoe** [comment]
CSS change: 
```
#header {
	height: unset!important;
}

#header .hu-pad {
	height: unset;
	padding: 10px 20px;
}
```
