### ISSUE TITLE
AppCenter hyperlinks (within software detail page) not following site style

### ISSUE THREAD

**Issue by fidoedidoe** [BodhiDev/bodhi-wp#4]
**Desired outcome**: In each AppCentre Software detail page ([example](https://www.bodhilinux.com/a/chromium/)), hyperlinks should match site-wide styling (orange, no underline when viewed, and orange underline on mouseover)

**Impact area**: Desktop / Tablet / Mobile view

**Verified using**: Chrome Desktop / Chrome Mobile App 

**Notes**:
The page is driven by a PHP function (single-appcenter.php) to pull in custom fields (?) and allow software installation via the browser. The PHP function defines HTML/CSS and I suspect this is where the issue resides. Ideally, the entire PHP function is removed (if like functionality can be achieved without it).

**Comment by ErwanGleo** [comment]
Done on staging, changed the colors to get a more "Bodhi-friendly" style and hover effect.
